include:
  - project: 'apro/devops'
    file: '/main.yml'

variables:
  IMAGE: registry.apro-dev.ir/apro/apro-front
  SERVICE: "apro-front"

build:
  stage: build
  script:
    - docker build -t $IMAGE:latest --build-arg "API_URL=http://apro-dev.ir/api" .
