include:
  - project: 'apro/devops'
    file: '/main.yml'

variables:
  IMAGE: registry.apro-dev.ir/apro/apro-front
  SERVICE: "apro-front"

build:
  stage: build
  script:
    - >
      docker build
      -t $IMAGE:$TAG
      --build-arg "PUBLIC_PATH=https://apro.ir/static/fr" .

sync-cdn:
  stage: sync-cdn
  script:
    - docker pull $IMAGE:$TAG
    - docker container create --name apro $IMAGE
    - docker container cp apro:/app/.nuxt/dist/client/. /var/www/static/fr
    - docker container rm -f apro
  tags:
    - asia-tech
  only:
    - master


### STAGING
build-stg:
  stage: build
  script:
    - >
      docker build
      -t $IMAGE:$TAG_STG
      --build-arg "PUBLIC_PATH=https://apro-dev.ir/static/fr" .
  only:
    - staging

sync-cdn-stg:
  stage: sync-cdn
  script:
    - docker pull $IMAGE:$TAG_STG
    - docker container create --name apro $IMAGE:$TAG_STG
    - docker container cp apro:/app/.nuxt/dist/client/. /var/www/static/fr
    - docker container rm -f apro
  only:
    - staging
