include:
  - project: 'aproo/devops'
    file: '/main.yml'

variables:
  IMAGE: apro-front

build:
  stage: build
  script:
    - docker build -t $IMAGE:latest --build-arg "API_URL=http://212.33.194.76/api" .