include:
  - project: 'apro/devops'
    file: '/main.yml'

variables:
  IMAGE: registry.apro-dev.ir/apro/apro-front
  SERVICE: "apro-front"

build:
  stage: build
  script:
    - >
      docker build -t $IMAGE:latest
        --build-arg "API_URL=https://apro-dev.ir/api"
        --build-arg "STATIC_URL=https://apro-dev.ir/static"
        --build-arg "PUBLIC_PATH=https://apro-dev.ir/static" .

sync-cdn:
  stage: sync-cdn
  script:
    - docker pull $IMAGE
    - docker container create --name apro $IMAGE
    - docker container cp apro:/app/.nuxt/dist/client /var/www/static/fr
    - docker container rm -f apro
  tags:
    - asia-tech
  only:
    - master
